requirejs.config({
	urlArgs: "v=" +  4,
	baseUrl:contextPath+"/",
	
    paths: {
        'menu': 'menu/menu',
        'menu-attr': 'menu/menu_attr',
        'menuType': 'menu/menuType',
        'packingboxfee': 'menu/packingboxfee',
        'menuTmpl': 'template/menu',
        'menuTypeTmpl': 'template/menuType',
        'combo': 'menu/combo',
        'acct': 'mchnt/acct',
        'frchse': 'mchnt/frchse',
        'oper': 'mchnt/oper',
        'mchnt': 'mchnt/mchnt',
        'order': 'trade/order',
        'prom': 'prom/prom',
        'discount': 'prom/discount',
        'turnover': 'report/turnover',
        'turnover-day': 'report/turnover_day',
        'turnover-month': 'report/turnover_month',
        'sales': 'report/sales',
        'terminal': 'mchnt/terminal',
        'mchnt-logo': 'mchnt/mchnt_logo',
        'audit-info': 'audit/audit_info',
        'audit-status': 'audit/audit_status',
        'audit-submit': 'audit/audit_submit',
        'audit-list': 'audit/audit_list',
        'admin-terminal': 'admin/terminal',
        'admin-mchnt': 'admin/mchnt',
        'admin-order': 'admin/order',
        'assoc-list': 'assoc/assoc',
        'assoc-apply': 'assoc/assoc_apply'
    }
});